<?php

declare(strict_types=1);

namespace Studiometa\FoehnInstaller;

use Composer\IO\IOInterface;
use FilesystemIterator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

/**
 * Generates the WordPress web root directory structure.
 *
 * Creates:
 * - web/index.php
 * - web/wp-config.php
 * - web/wp-content/themes/{theme-name} → symlink to ../../theme/
 * - web/wp-content/mu-plugins/00-loader.php
 * - web/wp-content/mu-plugins/_custom → symlink to ../../mu-plugins/
 * - web/wp-content/foehn/editor.js ← copied from the studiometa/foehn package
 *
 * Generates the WordPress security keys into .env on a first install, and removes
 * web/wp-content/cache/foehn/, whose contents describe the code that has just been
 * replaced.
 */
final class WebRootGenerator
{
    /**
     * The keys WordPress signs authentication cookies and nonces with.
     *
     * The same list as `Studiometa\Foehn\Security\Salts::NAMES`, repeated because a
     * Composer plugin cannot rely on the project's autoloader.
     *
     * @var list<string>
     */
    private const SALT_NAMES = [
        'AUTH_KEY',
        'SECURE_AUTH_KEY',
        'LOGGED_IN_KEY',
        'NONCE_KEY',
        'AUTH_SALT',
        'SECURE_AUTH_SALT',
        'LOGGED_IN_SALT',
        'NONCE_SALT',
    ];

    public function __construct(
        private readonly IOInterface $io,
        private readonly string $projectRoot,
        private readonly InstallerConfig $config,
        /** Install path of the `studiometa/foehn` package, or null if it cannot be resolved. */
        private readonly ?string $foehnPackagePath = null,
    ) {}

    /**
     * Generate the complete web root structure.
     */
    public function generate(): void
    {
        $this->io->write('<info>Foehn:</info> Generating web root...');

        $this->createDirectories();
        $this->generateIndexPhp();
        $this->generateWpConfig();
        $this->copyEnvFile();
        $this->symlinkTheme();
        $this->symlinkMuPlugins();
        $this->generateMuPluginLoader();
        $this->generateAdvancedCache();
        $this->generateEditorScript();
        $this->generateSalts();
        $this->clearCaches();

        $this->io->write('<info>Foehn:</info> Web root generated successfully.');
    }

    /**
     * Create the required directory structure.
     */
    private function createDirectories(): void
    {
        $dirs = [
            $this->webPath(),
            $this->webPath('wp-content'),
            $this->webPath('wp-content/themes'),
            $this->webPath('wp-content/plugins'),
            $this->webPath('wp-content/mu-plugins'),
            $this->webPath('wp-content/uploads'),
            $this->webPath('wp-content/foehn'),
        ];

        foreach ($dirs as $dir) {
            if (is_dir($dir)) {
                continue;
            }

            mkdir($dir, 0o755, true);
            $this->io->write("  <comment>Created:</comment> {$this->relativePath($dir)}");
        }
    }

    /**
     * Generate web/index.php.
     */
    private function generateIndexPhp(): void
    {
        $wpDir = $this->config->wpDir;
        $path = $this->webPath('index.php');

        $content = <<<PHP
            <?php

            /**
             * Front controller — auto-generated by foehn-installer.
             * DO NOT EDIT — this file is regenerated on `composer install`.
             */

            define('WP_USE_THEMES', true);
            require __DIR__ . '/{$wpDir}/wp-blog-header.php';

            PHP;

        $this->writeFile($path, $content);
    }

    /**
     * Generate web/wp-config.php.
     */
    private function generateWpConfig(): void
    {
        $path = $this->webPath('wp-config.php');
        $wpDir = $this->config->wpDir;
        $configDir = $this->config->configDir;
        $themeDir = $this->config->themeDir;

        $content = <<<'PHP'
            <?php

            /**
             * WordPress configuration — auto-generated by foehn-installer.
             * DO NOT EDIT — this file is regenerated on `composer install`.
             *
             * Project configuration lives in config/*.config.php files.
             * See: https://github.com/studiometa/foehn-framework
             */

            // Load Composer autoloader
            require_once dirname(__DIR__) . '/vendor/autoload.php';

            // Load .env file (vlucas/phpdotenv is a dependency of studiometa/foehn).
            // This runs before the project configuration below, so config/*.config.php
            // can read the project's own environment through $env().
            if (file_exists(dirname(__DIR__) . '/.env')) {
                $dotenv = Dotenv\Dotenv::createImmutable(dirname(__DIR__));
                $dotenv->safeLoad();
            }

            // Environment helper
            $env = function (string $key, mixed $default = null): mixed {
                $value = $_ENV[$key] ?? $_SERVER[$key] ?? getenv($key);
                return $value !== false ? $value : $default;
            };

            PHP;

        // Add config loading if config directory exists
        $configPath = $this->projectRoot . '/' . $configDir;
        if (is_dir($configPath)) {
            $content .= <<<PHP

                // Load project configuration
                \$configDir = dirname(__DIR__) . '/{$configDir}';

                // Load base wordpress config
                if (file_exists(\$configDir . '/wordpress.config.php')) {
                    require_once \$configDir . '/wordpress.config.php';
                }

                // Load environment-specific overrides
                \$environment = \$env('WP_ENVIRONMENT_TYPE', 'production');
                \$envConfig = \$configDir . "/wordpress.{\$environment}.config.php";
                if (file_exists(\$envConfig)) {
                    require_once \$envConfig;
                }

                PHP;
        }

        $content .= <<<PHP

            // Database
            define('DB_NAME', \$env('DB_NAME', 'wordpress'));
            define('DB_USER', \$env('DB_USER', 'root'));
            define('DB_PASSWORD', \$env('DB_PASSWORD', ''));
            define('DB_HOST', \$env('DB_HOST', 'localhost'));
            define('DB_CHARSET', \$env('DB_CHARSET', 'utf8mb4'));
            define('DB_COLLATE', '');

            // URLs
            define('WP_HOME', \$env('WP_HOME', 'http://localhost'));
            define('WP_SITEURL', \$env('WP_SITEURL', WP_HOME . '/{$wpDir}'));

            // Content directory
            define('WP_CONTENT_DIR', __DIR__ . '/wp-content');
            define('WP_CONTENT_URL', WP_HOME . '/wp-content');

            // Object storage for uploads — the constants humanmade/s3-uploads reads.
            //
            // Uploads are the one directory a generated web root does not make
            // disposable, so a deploy target with no persistent disk needs them
            // elsewhere. With no bucket configured nothing is defined here and the
            // plugin, installed or not, leaves uploads on local disk.
            //
            // A value already defined by config/*.config.php wins, and a value absent
            // from the environment is left undefined rather than defined as null —
            // which is what lets S3_UPLOADS_USE_INSTANCE_PROFILE supply the
            // credentials, and the plugin derive its own bucket URL.
            if (\$env('S3_UPLOADS_BUCKET')) {
                foreach ([
                    'S3_UPLOADS_BUCKET' => \$env('S3_UPLOADS_BUCKET'),
                    'S3_UPLOADS_REGION' => \$env('S3_UPLOADS_REGION', 'auto'),
                    'S3_UPLOADS_KEY' => \$env('AWS_ACCESS_KEY_ID'),
                    'S3_UPLOADS_SECRET' => \$env('AWS_SECRET_ACCESS_KEY'),
                    'S3_UPLOADS_BUCKET_URL' => \$env('S3_UPLOADS_BUCKET_URL'),
                    // Set when a webserver or CDN maps /wp-content/uploads/ to the
                    // bucket: WordPress then keeps writing its own URLs, and the
                    // media library stays on the site's own domain.
                    'S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL' => \$env('S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL'),
                ] as \$constant => \$value) {
                    if (\$value !== null && !defined(\$constant)) {
                        define(\$constant, \$value);
                    }
                }
            }

            // Security keys — from config/wordpress-salts.config.php, or the environment
            \$saltsFile = dirname(__DIR__) . '/{$configDir}/wordpress-salts.config.php';

            if (file_exists(\$saltsFile)) {
                require_once \$saltsFile;
            }

            \$missingSalts = [];

            foreach ([
                'AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY',
                'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT',
            ] as \$salt) {
                if (defined(\$salt)) {
                    continue;
                }

                \$value = \$env(\$salt);

                if (!is_string(\$value) || \$value === '' || str_starts_with(\$value, 'change-me-')) {
                    \$missingSalts[] = \$salt;
                    continue;
                }

                define(\$salt, \$value);
            }

            if (\$missingSalts !== []) {
                // These keys sign login cookies. Guessable ones can be forged, so a
                // production request is refused rather than served with them. WP-CLI
                // is exempt, because that is where `wp foehn salts:generate` runs.
                if (!defined('WP_CLI') && \$env('WP_ENVIRONMENT_TYPE', 'production') === 'production') {
                    http_response_code(500);
                    echo "WordPress security keys are not configured. Run: wp foehn salts:generate\\n";
                    exit(1);
                }

                foreach (\$missingSalts as \$salt) {
                    define(\$salt, 'insecure-development-key-' . \$salt . '-' . md5(__DIR__));
                }
            }

            // Table prefix
            \$table_prefix = \$env('DB_PREFIX', 'wp_');

            // Environment
            define('WP_ENVIRONMENT_TYPE', \$env('WP_ENVIRONMENT_TYPE', 'production'));

            // Debug
            \$isDebug = filter_var(\$env('WP_DEBUG', false), FILTER_VALIDATE_BOOLEAN);
            define('WP_DEBUG', \$isDebug);
            define('WP_DEBUG_DISPLAY', \$isDebug && WP_ENVIRONMENT_TYPE !== 'production');
            define('WP_DEBUG_LOG', \$isDebug);
            define('SCRIPT_DEBUG', \$isDebug);

            // Security
            define('DISALLOW_FILE_EDIT', true);
            define('DISALLOW_FILE_MODS', WP_ENVIRONMENT_TYPE === 'production');

            // Performance
            define('WP_POST_REVISIONS', (int) \$env('WP_POST_REVISIONS', 5));

            // Load wp-content/advanced-cache.php, which is Foehn's page cache drop-in.
            // Defined unconditionally: with no drop-in this is inert, and with a drop-in
            // whose config leaves the cache off it returns before doing anything. The
            // switch that matters is in {$themeDir}/app/page-cache.config.php.
            define('WP_CACHE', true);

            // ABSPATH
            if (!defined('ABSPATH')) {
                define('ABSPATH', __DIR__ . '/{$wpDir}/');
            }

            require_once ABSPATH . 'wp-settings.php';

            PHP;

        $this->writeFile($path, $content);
    }

    /**
     * Copy .env.example to .env if .env doesn't exist.
     */
    private function copyEnvFile(): void
    {
        $envFile = $this->projectRoot . '/.env';
        $envExample = $this->projectRoot . '/.env.example';

        if (file_exists($envFile)) {
            return;
        }

        if (!file_exists($envExample)) {
            return;
        }

        copy($envExample, $envFile);
        $this->io->write('  <comment>Created:</comment> .env (from .env.example)');
    }

    /**
     * Create theme symlink.
     */
    private function symlinkTheme(): void
    {
        $themeSource = $this->projectRoot . '/' . $this->config->themeDir;
        $themeTarget = $this->webPath('wp-content/themes/' . $this->config->themeName);

        if (!is_dir($themeSource)) {
            $this->io->write("  <warning>Skipped theme symlink:</warning> {$this->config->themeDir}/ not found");

            return;
        }

        $this->createSymlink($themeSource, $themeTarget);
        $this->removeStaleThemeSymlinks($themeTarget);
    }

    /**
     * Remove theme symlinks left by a previous `theme-name`.
     *
     * Renaming `extra.foehn.theme-name` used to leave the old link in place, so
     * `wp theme list` showed the same directory twice and `wp theme activate`
     * could pick the name nobody uses any more.
     *
     * Only links pointing at the theme directory are removed: a symlink to
     * anything else was put there by the project, not by this installer.
     */
    private function removeStaleThemeSymlinks(string $keep): void
    {
        $themesDir = $this->webPath('wp-content/themes');
        $entries = is_dir($themesDir) ? scandir($themesDir) : false;

        if ($entries === false) {
            return;
        }

        $themeSource = realpath($this->projectRoot . '/' . $this->config->themeDir);

        foreach ($entries as $entry) {
            if ($entry === '.' || $entry === '..') {
                continue;
            }

            $path = $themesDir . '/' . $entry;

            if ($path === $keep || !is_link($path) || realpath($path) !== $themeSource) {
                continue;
            }

            unlink($path);
            $this->io->write("  <comment>Removed stale symlink:</comment> {$this->relativePath($path)}");
        }
    }

    /**
     * Create mu-plugins symlink.
     */
    private function symlinkMuPlugins(): void
    {
        $muSource = $this->projectRoot . '/' . $this->config->muPluginsDir;
        $muTarget = $this->webPath('wp-content/mu-plugins/_custom');

        if (!is_dir($muSource)) {
            return;
        }

        $this->createSymlink($muSource, $muTarget);
    }

    /**
     * Generate the mu-plugin loader that loads custom mu-plugins.
     */
    private function generateMuPluginLoader(): void
    {
        $muSource = $this->projectRoot . '/' . $this->config->muPluginsDir;

        if (!is_dir($muSource)) {
            return;
        }

        $path = $this->webPath('wp-content/mu-plugins/00-loader.php');

        $content = <<<'PHP'
            <?php

            /**
             * MU-Plugin loader — auto-generated by foehn-installer.
             * DO NOT EDIT — this file is regenerated on `composer install`.
             *
             * Loads all PHP files from the _custom/ symlinked directory.
             */

            $customDir = __DIR__ . '/_custom';

            if (!is_dir($customDir)) {
                return;
            }

            foreach (glob($customDir . '/*.php') as $file) {
                require_once $file;
            }

            PHP;

        $this->writeFile($path, $content);
    }

    /**
     * Generate the `advanced-cache.php` drop-in WordPress loads before it boots.
     *
     * `wp-settings.php` includes this file when `WP_CACHE` is true, early enough that a
     * stored page can be sent without WordPress, the database or the theme ever loading.
     * The generated `wp-config.php` has already required the autoloader and defined
     * `WP_HOME`, so the drop-in only has to say where the project's config file lives —
     * everything else is the framework's.
     *
     * Written unconditionally, and inert unless a `page-cache*.config.php` turns the
     * cache on. A drop-in nobody asked for that returns immediately costs one `is_file()`
     * per request; a drop-in that has to be installed by hand costs a support ticket.
     */
    private function generateAdvancedCache(): void
    {
        $path = $this->webPath('wp-content/advanced-cache.php');
        $themeDir = $this->config->themeDir;

        $content = <<<PHP
            <?php

            /**
             * Page cache drop-in — auto-generated by foehn-installer.
             * DO NOT EDIT — this file is regenerated on `composer install`.
             *
             * Loaded by wp-settings.php when WP_CACHE is true. Serves a stored page and
             * exits, or returns and lets WordPress boot. Configuration lives in
             * {$themeDir}/app/page-cache.config.php — this file holds no policy.
             */

            if (class_exists(Studiometa\\Foehn\\PageCache\\Server::class)) {
                Studiometa\\Foehn\\PageCache\\Server::boot(dirname(__DIR__, 2) . '/{$themeDir}/app');
            }

            PHP;

        $this->writeFile($path, $content);
    }

    /**
     * Copy the generic block editor registrar script from the `studiometa/foehn` package
     * into the web root, so it can be served to the browser.
     *
     * `vendor/studiometa/foehn/` sits outside the document root, so the script is copied
     * into `web/wp-content/foehn/editor.js`, giving it a real, cacheable URL:
     * `content_url('foehn/editor.js')`.
     */
    private function generateEditorScript(): void
    {
        if ($this->foehnPackagePath === null) {
            $this->io->write(
                '  <warning>Skipped editor script:</warning> studiometa/foehn package path could not be resolved',
            );

            return;
        }

        $source = $this->foehnPackagePath . '/resources/js/editor.js';

        if (!file_exists($source)) {
            $this->io->write(
                "  <warning>Skipped editor script:</warning> {$source} not found — update studiometa/foehn",
            );

            return;
        }

        $script = file_get_contents($source);

        if ($script === false) {
            $this->io->write("  <warning>Skipped editor script:</warning> could not read {$source}");

            return;
        }

        $target = $this->webPath('wp-content/foehn/editor.js');
        $header = <<<'JS'
            /**
             * Block editor registrar — auto-generated by foehn-installer.
             * DO NOT EDIT — this file is regenerated on `composer install`.
             */


            JS;

        $this->writeRawFile($target, $header . $script);
    }

    /**
     * Write the WordPress security keys, once.
     *
     * They go into .env, which is where wp-config.php reads them from and where the
     * project already keeps its other secrets. A project that supplies them another
     * way — container variables, a vault, the PHP config file — is left alone.
     *
     * Never rewritten: doing so on every `composer install` would log every user out
     * on every deploy.
     *
     * This repeats what `Studiometa\Foehn\Security\Salts` does, because a Composer
     * plugin cannot rely on the project's autoloader being available to it. The line
     * format is the contract, and `wp foehn salts:generate` writes the same one.
     */
    private function generateSalts(): void
    {
        if (is_file($this->projectRoot . '/' . $this->config->configDir . '/wordpress-salts.config.php')) {
            return;
        }

        if ($this->environmentHasSalts()) {
            return;
        }

        $path = $this->projectRoot . '/.env';
        $contents = is_file($path) ? (string) file_get_contents($path) : '';
        $lines = [];
        $remplacees = 0;

        foreach (self::SALT_NAMES as $name) {
            // A name may be listed but empty, which is how .env.example carries them.
            if (preg_match('/^[ \t]*' . $name . '[ \t]*=[ \t]*\S/m', $contents) === 1) {
                continue;
            }

            $line = sprintf('%s="%s"', $name, base64_encode(random_bytes(48)));
            $pattern = '/^[ \t]*' . $name . '[ \t]*=.*$/m';

            if (preg_match($pattern, $contents) === 1) {
                $contents = (string) preg_replace($pattern, $line, $contents, 1);
                $remplacees++;

                continue;
            }

            $lines[] = $line;
        }

        // Rien à écrire quand tout est déjà en place. Le message le disait
        // pourtant à chaque exécution, ce qui rendait impossible de repérer celle
        // qui avait réellement réécrit les clés.
        if ($lines === [] && $remplacees === 0) {
            $this->io->write('  <comment>Security keys:</comment> already set');

            return;
        }

        if ($lines !== []) {
            $contents =
                rtrim($contents, "\n")
                . "\n\n# WordPress security keys — secret, and specific to this install\n"
                . implode("\n", $lines)
                . "\n";
        }

        file_put_contents($path, $contents);

        $this->io->write('  <comment>Generated:</comment> security keys in .env');
    }

    /**
     * Whether every security key is already set in the environment.
     *
     * A partial set counts as absent: the rest have to come from somewhere, and
     * wp-config.php refuses a production request that is missing any of them.
     */
    private function environmentHasSalts(): bool
    {
        // Exported variables count: a project injecting them from a vault or a
        // container has them in the environment Composer itself runs in.
        foreach (self::SALT_NAMES as $name) {
            if (getenv($name) === false) {
                return false;
            }
        }

        return true;
    }

    /**
     * Drop Foehn's caches, because the code that produced them has just changed.
     *
     * Both of them live under `wp-content/cache/foehn/`: the discovery cache describes
     * classes that may no longer exist, and the page cache holds HTML rendered by
     * templates that may no longer render it that way. Neither survives a deploy.
     *
     * Foehn refills both by itself — a request that finds the discovery cache missing
     * writes it, and a request that finds no stored page renders and stores one — so
     * this is the whole of cache invalidation on a deploy. Nothing has to boot
     * WordPress for it; the files are simply removed.
     *
     * Only the default location is cleared. A project that set
     * `FoehnConfig::$discoveryCachePath` or `PageCacheConfig::$path` chose a path this
     * plugin cannot read, and owns clearing it.
     */
    private function clearCaches(): void
    {
        $path = $this->webPath('wp-content/cache/foehn');

        if (!is_dir($path)) {
            return;
        }

        if (!is_writable($path)) {
            $this->io->write(
                "  <warning>Could not clear:</warning> {$this->relativePath($path)} is not writable — "
                . 'run `wp foehn discovery:clear && wp foehn cache:clear`',
            );

            return;
        }

        $entries = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST,
        );

        /** @var SplFileInfo $entry */
        foreach ($entries as $entry) {
            if ($entry->isDir() && !$entry->isLink()) {
                rmdir($entry->getPathname());

                continue;
            }

            unlink($entry->getPathname());
        }

        rmdir($path);

        $this->io->write("  <comment>Cleared:</comment> {$this->relativePath($path)}");
    }

    /**
     * Create a symlink, replacing existing one if needed.
     */
    private function createSymlink(string $source, string $target): void
    {
        // Skip if target is a real directory (not a symlink)
        if (!is_link($target) && is_dir($target)) {
            $this->io->write(
                "  <warning>Skipped symlink:</warning> {$this->relativePath($target)} already exists as directory",
            );

            return;
        }

        // Remove existing symlink
        if (is_link($target)) {
            unlink($target);
        }

        // Create relative symlink
        $relativeSource = $this->makeRelativePath(dirname($target), $source);
        symlink($relativeSource, $target);
        $this->io->write("  <comment>Symlinked:</comment> {$this->relativePath($target)} → {$relativeSource}");
    }

    /**
     * Write a file and report it.
     */
    private function writeFile(string $path, string $content): void
    {
        // Normalize indentation (remove leading spaces from heredoc)
        $content = $this->normalizeIndentation($content);

        $existed = file_exists($path);
        file_put_contents($path, $content);

        $action = $existed ? 'Updated' : 'Created';
        $this->io->write("  <comment>{$action}:</comment> {$this->relativePath($path)}");
    }

    /**
     * Write a file verbatim and report it, without heredoc indentation normalization.
     *
     * Used for content copied from real source files, where stripping leading
     * whitespace would corrupt the file instead of merely tidying a template.
     */
    private function writeRawFile(string $path, string $content): void
    {
        $existed = file_exists($path);
        file_put_contents($path, $content);

        $action = $existed ? 'Updated' : 'Created';
        $this->io->write("  <comment>{$action}:</comment> {$this->relativePath($path)}");
    }

    /**
     * Normalize heredoc indentation.
     */
    private function normalizeIndentation(string $content): string
    {
        $lines = explode("\n", $content);
        if (count($lines) < 2) {
            return $content;
        }

        // Find minimum indentation (excluding empty lines and first line)
        $minIndent = PHP_INT_MAX;
        foreach ($lines as $i => $line) {
            if ($i === 0 || trim($line) === '') {
                continue;
            }
            $indent = strlen($line) - strlen(ltrim($line));
            if ($indent < $minIndent) {
                $minIndent = $indent;
            }
        }

        if ($minIndent === 0 || $minIndent === PHP_INT_MAX) {
            return $content;
        }

        // Remove common indentation
        return implode("\n", array_map(static fn(string $line): string => trim($line) === ''
            ? ''
            : substr($line, $minIndent), $lines));
    }

    /**
     * Get a path relative to the web directory.
     */
    private function webPath(string $path = ''): string
    {
        $base = $this->projectRoot . '/' . $this->config->webDir;

        return $path !== '' ? $base . '/' . $path : $base;
    }

    /**
     * Get a path relative to the project root (for display).
     */
    private function relativePath(string $path): string
    {
        return str_replace($this->projectRoot . '/', '', $path);
    }

    /**
     * Make a relative path from one location to another.
     */
    private function makeRelativePath(string $from, string $to): string
    {
        $from = rtrim($from, '/');
        $to = rtrim($to, '/');

        $fromParts = explode('/', $from);
        $toParts = explode('/', $to);

        // Find common prefix
        $common = 0;
        $max = min(count($fromParts), count($toParts));
        while ($common < $max && $fromParts[$common] === $toParts[$common]) {
            $common++;
        }

        // Build relative path
        $ups = count($fromParts) - $common;
        $remaining = array_slice($toParts, $common);

        $parts = array_merge(array_fill(0, $ups, '..'), $remaining);

        return implode('/', $parts);
    }
}
